In [3]:
a=[0]*10
b=10

In [2]:
a

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [4]:
x = f'hello{a} and{b}'.format()

In [5]:
x

'hello[0, 0, 0, 0, 0, 0, 0, 0, 0, 0] and10'

In [7]:
y = {'a':"a",'b':"b"}
y['a']

'a'

In [8]:
range(0,5)

range(0, 5)

In [12]:
seq = [1,2,3,4,5]

In [17]:
def times2(var):return var*2

In [19]:
t = lambda var:var*2

In [18]:
list(map(times2,seq))

[2, 4, 6, 8, 10]

In [20]:
t(60)

120

In [22]:
hi = 'hi my name is Prashanth'
for i in hi.split():
    print(i)

hi
my
name
is
Prashanth


In [25]:
!ls Python-Data-Science-and-Machine-Learning-Bootcamp/Python-Crash-Course

Python Crash Course Exercises - Solutions.ipynb
Python Crash Course Exercises .ipynb
Python Crash Course.ipynb


In [55]:
list1 = [1,2,3]
list2 = [3,4,5]
list3 = [*list1, *list2]
list3

[1, 2, 3, 3, 4, 5]

In [2]:
(a,b,c) = *list1

SyntaxError: invalid syntax (<ipython-input-2-f8ba4b8b8edb>, line 1)

In [7]:
args=[3,10]
args2={2:20}
list(range(*args1))
**args2

SyntaxError: invalid syntax (<ipython-input-7-c7a55ff17d87>, line 4)

In [47]:
dict1 = {'a':1,'b':2,'c':3}
dict2 = {'c':4,'d':5}
z = {**dict1,**dict2}
z

{'a': 1, 'b': 2, 'c': 4, 'd': 5}

In [17]:
pairs = [(1, 'one'), (2, 'two'),(4, 'four'),(3, 'three')]
pairs[1]

(2, 'two')

In [18]:
pairs.sort(key=lambda pair:pair[1])
pairs

[(4, 'four'), (1, 'one'), (3, 'three'), (2, 'two')]

# NumPy

In [2]:
import numpy as np

In [28]:
lis1 = [1,2,3]
lis1

[1, 2, 3]

In [29]:
arr = np.array(lis1)
arr

array([1, 2, 3])

In [5]:
arr1 = np.arange(0,10,2,dtype='f')
arr1

array([0., 2., 4., 6., 8.], dtype=float32)

In [25]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [36]:
arr2 = np.bool(10)
arr2

True

In [38]:
np.random.rand(2,2,3)

array([[[0.6176952 , 0.4869962 , 0.11961286],
        [0.53545723, 0.74230308, 0.21995261]],

       [[0.75179797, 0.44187446, 0.40276602],
        [0.60749942, 0.01014272, 0.76759323]]])

In [26]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [28]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])