# Numpy 

In [1]:
import numpy as np

In [2]:
np.arange(0,10,2,dtype='f')

array([0., 2., 4., 6., 8.], dtype=float32)

In [63]:
#  to change arange to 2D use reshape

In [121]:
zeros= np.zeros((5,5))

In [124]:
zeros.size, zeros.shape

(25, (5, 5))

In [4]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [8]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
np.random.rand(10,2) # dist of 0 to 1 -> uniform dist

array([[0.44887957, 0.94275237],
       [0.46057236, 0.13678249],
       [0.535082  , 0.35727332],
       [0.01197919, 0.33912383],
       [0.11618603, 0.10249879],
       [0.86105613, 0.06343963],
       [0.29546359, 0.32113684],
       [0.3375941 , 0.9001963 ],
       [0.9636074 , 0.37568267],
       [0.66394673, 0.77362492]])

In [13]:
np.random.randn(2,2) # Normal dist

array([[ 1.37614273, -1.69502542],
       [ 1.14786786, -0.09451578]])

In [20]:
arr = np.random.randint(0,100,10)
arr

array([12, 99, 41, 54, 59, 62, 48, 28, 21, 74])

In [18]:
arr.reshape(5,2) # 5*2 = length

array([[75, 71],
       [ 5, 87],
       [67, 77],
       [22, 47],
       [15, 18]])

In [29]:
arr.max(),arr.min(),arr.argmax(),arr.argmin()

(99, 12, 1, 0)

In [30]:
arr.shape # note  attributr no ()

(10,)

In [31]:
arr.dtype

dtype('int64')

In [34]:
from numpy import random as rnd

In [35]:
rnd.rand(10,2)

array([[0.39895265, 0.73006911],
       [0.01776487, 0.67831546],
       [0.1731783 , 0.92948993],
       [0.39316089, 0.80931331],
       [0.27805677, 0.34845074],
       [0.17684297, 0.51031541],
       [0.03064936, 0.36828119],
       [0.67426635, 0.08519089],
       [0.60948366, 0.87338759],
       [0.82286485, 0.20839057]])

In [40]:
arr2 = np.arange(2,10)
print(arr2)
arr3 = arr2
arr3[2:5] = 100 # brodcasting
print(arr2) 
print(arr3) 

[2 3 4 5 6 7 8 9]
[  2   3 100 100 100   7   8   9]
[  2   3 100 100 100   7   8   9]


In [41]:
# to make copy use copy()
arr4 = arr3.copy()

In [53]:
 arr5=rnd.rand(4,4)
 print(arr5,'\n')
 print(arr5[1,1],'\n')
 print(arr5[:,0])

[[0.16029401 0.83941247 0.42027533 0.63609909]
 [0.24103215 0.70939549 0.05755136 0.39983774]
 [0.04104889 0.64770753 0.70025111 0.8726944 ]
 [0.04136448 0.74030194 0.13106622 0.25561742]] 

0.7093954929737436 

[0.16029401 0.24103215 0.04104889 0.04136448]


In [62]:
bool_arr = arr5 > 0.5
print(arr5,'\n')
print(bool_arr,'\n')
print(arr5[bool_arr],'\n')
print(arr5[arr5>0.5])


[[0.16029401 0.83941247 0.42027533 0.63609909]
 [0.24103215 0.70939549 0.05755136 0.39983774]
 [0.04104889 0.64770753 0.70025111 0.8726944 ]
 [0.04136448 0.74030194 0.13106622 0.25561742]] 

[[False  True False  True]
 [False  True False False]
 [False  True  True  True]
 [False  True False False]] 

[0.83941247 0.63609909 0.70939549 0.64770753 0.70025111 0.8726944
 0.74030194] 

[0.83941247 0.63609909 0.70939549 0.64770753 0.70025111 0.8726944
 0.74030194]


In [65]:
arr6 = np.arange(11)
arr6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
arr6+arr6, arr6-arr6, arr6*arr6, arr6 -100, arr6**2

(array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100]),
 array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90]),
 array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100]))

In [67]:
arr6/arr6

/Users/sprastar/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [69]:
np.sqrt(arr6) # np.sin(arr), np.exp(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [70]:
np.max(arr6)

10

In [72]:
dir(arr6)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_e

# Pandas

In [73]:
import pandas as pd

In [74]:
labels = ['a','b','c']
data = [10,20,30]

arr = np.array(data)
d={'a':10,'b':20,'c':30}

In [76]:
pd.Series(data,labels)

a    10
b    20
c    30
dtype: int64

In [77]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

## DataFrames

In [101]:
rnd.seed(101)

In [102]:
df = pd.DataFrame(rnd.randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [105]:
type(df[['W','Z']])

pandas.core.frame.DataFrame

In [108]:
df[['W','Z']]

W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [113]:
df['new'] = df['W'] + df['Z']
df

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.210676
B  0.651118 -0.319318 -0.848077  0.605965  1.257083
C -2.018168  0.740122  0.528813 -0.589001 -2.607169
D  0.188695 -0.758872 -0.933237  0.955057  1.143752
E  0.190794  1.978757  2.605967  0.683509  0.874303

In [116]:
df.drop('new',axis=1,inplace=True)

In [117]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [118]:
df.shape

(5, 4)

In [132]:
# column df['X'] for rows df.loc['A']

In [131]:
df.loc['A'] 

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [133]:
df.iloc[0]

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [143]:
df.loc['A']

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [138]:
df > 0

W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [145]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [169]:
cols=['X','Y']
df[(df['W']>0) & (df['Z']>0.7)]

W         X         Y         Z
D  0.188695 -0.758872 -0.933237  0.955057