# Numpy 

In [1]:
import numpy as np

In [2]:
np.arange(0,10,2,dtype='f')

array([0., 2., 4., 6., 8.], dtype=float32)

In [3]:
#  to change arange to 2D use reshape

In [4]:
zeros= np.zeros((5,5))

In [5]:
zeros.size, zeros.shape

(25, (5, 5))

In [6]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [8]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
np.random.rand(10,2) # dist of 0 to 1 -> uniform dist

array([[0.47054733, 0.21635018],
       [0.06764322, 0.172782  ],
       [0.83586352, 0.48675856],
       [0.58150088, 0.1706187 ],
       [0.10293807, 0.9448586 ],
       [0.74028619, 0.74244735],
       [0.08343906, 0.233042  ],
       [0.06025371, 0.2231939 ],
       [0.94656244, 0.48694365],
       [0.80168938, 0.4605529 ]])

In [10]:
np.random.randn(2,2) # Normal dist

array([[-0.97513479, -0.88912369],
       [ 0.83995522,  0.18177412]])

In [11]:
arr = np.random.randint(0,100,10)
arr

array([15, 87, 97, 64, 64, 15, 92, 45,  4, 44])

In [12]:
arr.reshape(5,2) # 5*2 = length

array([[15, 87],
       [97, 64],
       [64, 15],
       [92, 45],
       [ 4, 44]])

In [13]:
arr.max(),arr.min(),arr.argmax(),arr.argmin()

(97, 4, 2, 8)

In [14]:
arr.shape # note  attributr no ()

(10,)

In [15]:
arr.dtype

dtype('int64')

In [16]:
from numpy import random as rnd

In [17]:
rnd.rand(10,2)

array([[0.84206677, 0.20683244],
       [0.52103601, 0.56481094],
       [0.30052773, 0.511619  ],
       [0.61887042, 0.86477531],
       [0.96321249, 0.94038239],
       [0.42253912, 0.74776598],
       [0.4777228 , 0.10016819],
       [0.10359791, 0.78716631],
       [0.15008976, 0.19291659],
       [0.78572465, 0.03359273]])

In [18]:
arr2 = np.arange(2,10)
print(arr2)
arr3 = arr2
arr3[2:5] = 100 # brodcasting
print(arr2) 
print(arr3) 

[2 3 4 5 6 7 8 9]
[  2   3 100 100 100   7   8   9]
[  2   3 100 100 100   7   8   9]


In [19]:
# to make copy use copy()
arr4 = arr3.copy()

In [20]:
 arr5=rnd.rand(4,4)
 print(arr5,'\n')
 print(arr5[1,1],'\n')
 print(arr5[:,0])

[[0.52041154 0.89428112 0.58337156 0.59938257]
 [0.68954673 0.23526438 0.41881799 0.18920714]
 [0.43681305 0.4275793  0.74733462 0.10614465]
 [0.02564476 0.50306543 0.46071128 0.70984864]] 

0.23526438201159872 

[0.52041154 0.68954673 0.43681305 0.02564476]


In [21]:
bool_arr = arr5 > 0.5
print(arr5,'\n')
print(bool_arr,'\n')
print(arr5[bool_arr],'\n')
print(arr5[arr5>0.5])


[[0.52041154 0.89428112 0.58337156 0.59938257]
 [0.68954673 0.23526438 0.41881799 0.18920714]
 [0.43681305 0.4275793  0.74733462 0.10614465]
 [0.02564476 0.50306543 0.46071128 0.70984864]] 

[[ True  True  True  True]
 [ True False False False]
 [False False  True False]
 [False  True False  True]] 

[0.52041154 0.89428112 0.58337156 0.59938257 0.68954673 0.74733462
 0.50306543 0.70984864] 

[0.52041154 0.89428112 0.58337156 0.59938257 0.68954673 0.74733462
 0.50306543 0.70984864]


In [22]:
arr6 = np.arange(11)
arr6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
arr6+arr6, arr6-arr6, arr6*arr6, arr6 -100, arr6**2

(array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100]),
 array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90]),
 array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100]))

In [24]:
arr6/arr6

/Users/sprastar/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [25]:
np.sqrt(arr6) # np.sin(arr), np.exp(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [26]:
np.max(arr6)

10

In [27]:
dir(arr6)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_e

# Pandas

In [28]:
import pandas as pd

In [29]:
labels = ['a','b','c']
data = [10,20,30]

arr = np.array(data)
d={'a':10,'b':20,'c':30}

In [30]:
pd.Series(data,labels)

a    10
b    20
c    30
dtype: int64

In [31]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

## DataFrames

In [32]:
rnd.seed(101)

In [33]:
df = pd.DataFrame(rnd.randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [34]:
type(df[['W','Z']])

pandas.core.frame.DataFrame

In [35]:
df[['W','Z']]

W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [36]:
df['new'] = df['W'] + df['Z']
df

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.210676
B  0.651118 -0.319318 -0.848077  0.605965  1.257083
C -2.018168  0.740122  0.528813 -0.589001 -2.607169
D  0.188695 -0.758872 -0.933237  0.955057  1.143752
E  0.190794  1.978757  2.605967  0.683509  0.874303

In [37]:
df.drop('new',axis=1,inplace=True)

In [38]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [39]:
df.shape

(5, 4)

In [40]:
# column df['X'] for rows df.loc['A']

In [41]:
df.loc['A'] 

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [42]:
df.iloc[0]

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [43]:
df.loc['A']

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [44]:
df > 0

W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [45]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [46]:
cols=['X','Y']
df[(df['W']>0) & (df['Z']>0.7)]

W         X         Y         Z
D  0.188695 -0.758872 -0.933237  0.955057

In [50]:
df.reset_index()

index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

In [53]:
df.shape, df.size

((5, 4), 20)

In [58]:
newind = 'CA NY WY OR CO'.split()
newind

['CA', 'NY', 'WY', 'OR', 'CO']

In [60]:
df['States']=newind
df

W         X         Y         Z States
A  2.706850  0.628133  0.907969  0.503826     CA
B  0.651118 -0.319318 -0.848077  0.605965     NY
C -2.018168  0.740122  0.528813 -0.589001     WY
D  0.188695 -0.758872 -0.933237  0.955057     OR
E  0.190794  1.978757  2.605967  0.683509     CO

In [62]:
df.set_index('States')


W         X         Y         Z
States                                        
CA      2.706850  0.628133  0.907969  0.503826
NY      0.651118 -0.319318 -0.848077  0.605965
WY     -2.018168  0.740122  0.528813 -0.589001
OR      0.188695 -0.758872 -0.933237  0.955057
CO      0.190794  1.978757  2.605967  0.683509

In [69]:
# Index Levels
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)
hier_index

MultiIndex(levels=[['G1', 'G2'], [1, 2, 3]],
           labels=[[0, 0, 0, 1, 1, 1], [0, 1, 2, 0, 1, 2]])

In [80]:
hier_index[3]

('G2', 1)

In [72]:
df = pd.DataFrame(np.random.rand(6,2),hier_index,['A','B'])
df

A         B
G1 1  0.097146  0.102847
   2  0.701507  0.890480
   3  0.159560  0.275573
G2 1  0.672492  0.164303
   2  0.701371  0.487635
   3  0.680678  0.521548

In [83]:
df.loc['G1'].loc[1]

A    0.097146
B    0.102847
Name: 1, dtype: float64

In [90]:
df.index.names = ['Groups','Num']
df.index.names

FrozenList(['Groups', 'Num'])

In [91]:
df

A         B
Groups Num                    
G1     1    0.097146  0.102847
       2    0.701507  0.890480
       3    0.159560  0.275573
G2     1    0.672492  0.164303
       2    0.701371  0.487635
       3    0.680678  0.521548

In [93]:
df.loc['G2'].loc[2]['B']

0.4876352222057281

In [97]:
df.xs(1,level='Num')

A         B
Groups                    
G1      0.097146  0.102847
G2      0.672492  0.164303

## Missing Data

In [100]:
d = {'A':[1,2,np.nan],'B':[5,np.nan,np.nan],'C':[1,2,3]}
df2 = pd.DataFrame(d)
df2

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [105]:
df2.dropna(axis=1)

C
0  1
1  2
2  3

In [107]:

df2.fillna('0')

A  B  C
0  1  5  1
1  2  0  2
2  0  0  3

In [109]:
df2['A'].fillna(value=df['A'].mean())

0    1.000000
1    2.000000
2    0.502126
Name: A, dtype: float64

## Groupby 

In [110]:
  # Create dataframe
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]}

In [111]:
df3 = pd.DataFrame(data)
df3

Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [118]:
byComp = df3.groupby('Company')

In [119]:
byComp.mean()

Sales
Company       
FB       296.5
GOOG     160.0
MSFT     232.0

In [120]:
byComp.sum()

Sales
Company       
FB         593
GOOG       320
MSFT       464

In [128]:
df3.groupby('Company').count()

Person  Sales
Company               
FB            2      2
GOOG          2      2
MSFT          2      2

In [126]:
df3.groupby('Company').min()

Person  Sales
Company                
FB          Carl    243
GOOG     Charlie    120
MSFT         Amy    124

In [131]:
df3.groupby('Company').describe().transpose()

Company              FB        GOOG        MSFT
Sales count    2.000000    2.000000    2.000000
      mean   296.500000  160.000000  232.000000
      std     75.660426   56.568542  152.735065
      min    243.000000  120.000000  124.000000
      25%    269.750000  140.000000  178.000000
      50%    296.500000  160.000000  232.000000
      75%    323.250000  180.000000  286.000000
      max    350.000000  200.000000  340.000000

In [132]:
df3.groupby('Company').describe()

Sales                                                        
        count   mean         std    min     25%    50%     75%    max
Company                                                              
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [136]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])

In [137]:
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                         index=[4, 5, 6, 7]) 

In [138]:
df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                        'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']},
                        index=[8, 9, 10, 11])

In [141]:
df3

A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [143]:
pd.concat([df1,df2,df3],axis=0)

A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

##  Operations

In [145]:
df = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})
df.head()

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [146]:
df['col2'].unique()

array([444, 555, 666])

In [147]:
df['col2'].nunique()

3

In [148]:
df['col2'].value_counts()

444    2
555    1
666    1
Name: col2, dtype: int64

In [159]:
df[df['col2']>2]

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [160]:
def times2(x):return x*2

In [161]:
df['col1'].apply(times2)

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [162]:
df['col3'].apply(len)

0    3
1    3
2    3
3    3
Name: col3, dtype: int64

In [163]:
df['col1'].apply(lambda x: x*2)

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [167]:
df.drop('col1',axis=1,inplace=False)

col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  xyz

In [170]:
df.columns

Index(['col1', 'col2', 'col3'], dtype='object')

In [172]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [173]:
df.sort_values('col2')

col1  col2 col3
0     1   444  abc
3     4   444  xyz
1     2   555  def
2     3   666  ghi

In [174]:
df.isnull()

col1   col2   col3
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False

In [175]:
data = {'A':['foo','foo','foo','bar','bar','bar'],
     'B':['one','one','two','two','one','one'],
       'C':['x','y','x','y','x','y'],
       'D':[1,3,2,5,4,1]}

In [176]:
data

{'A': ['foo', 'foo', 'foo', 'bar', 'bar', 'bar'],
 'B': ['one', 'one', 'two', 'two', 'one', 'one'],
 'C': ['x', 'y', 'x', 'y', 'x', 'y'],
 'D': [1, 3, 2, 5, 4, 1]}

In [178]:
df=pd.DataFrame(data)
df

A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1

In [185]:
df.pivot_table(values='D',index=['A'],columns=['C','B'])

C      x         y     
B    one  two  one  two
A                      
bar  4.0  NaN  1.0  5.0
foo  1.0  2.0  3.0  NaN

## Input and Output 

In [191]:
df_csv = pd.read_csv('example')

In [199]:
df_csv.to_csv('My_output',index=False)

In [200]:
pd.read_csv('My_output')

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [209]:
df=pd.read_excel('Excel_Sample.xlsx',sheet_name='Sheet2')

In [210]:
df.to_excel('Excel_Sample.xlsx',sheet_name='Copied')

In [217]:
fdic_link='http://www.fdic.gov/bank/individual/failed/banklist.html'

In [218]:
data = pd.read_html(fdic_link)

In [223]:
data[0].head()

Bank Name         City  ST   CERT  \
0                Washington Federal Bank for Savings      Chicago  IL  30570   
1    The Farmers and Merchants State Bank of Argonia      Argonia  KS  17719   
2                                Fayette County Bank   Saint Elmo  IL   1802   
3  Guaranty Bank, (d/b/a BestBank in Georgia & Mi...    Milwaukee  WI  30003   
4                                     First NBC Bank  New Orleans  LA  58302   

                 Acquiring Institution       Closing Date       Updated Date  
0                   Royal Savings Bank  December 15, 2017  February 21, 2018  
1                          Conway Bank   October 13, 2017  February 21, 2018  
2            United Fidelity Bank, fsb       May 26, 2017      July 26, 2017  
3  First-Citizens Bank & Trust Company        May 5, 2017     March 22, 2018  
4                         Whitney Bank     April 28, 2017   December 5, 2017

In [227]:
 from sqlalchemy import create_engine

In [228]:
engine = create_engine('sqlite:///:memory')

In [230]:
df

A1   A2   A3   A4   A5
1  100  200  300  400  500
2  100  200  300  400  500
3  100  200  300  400  500
4  100  200  300  400  500
5  100  200  300  400  500
6  100  200  300  400  500
7  100  200  300  400  500
8  100  200  300  400  500
9  100  200  300  400  500

In [231]:
df.to_sql('my_table',engine)

In [232]:
sqldf=pd.read_sql('my_table',con=engine)

In [233]:
sqldf

index   A1   A2   A3   A4   A5
0      1  100  200  300  400  500
1      2  100  200  300  400  500
2      3  100  200  300  400  500
3      4  100  200  300  400  500
4      5  100  200  300  400  500
5      6  100  200  300  400  500
6      7  100  200  300  400  500
7      8  100  200  300  400  500
8      9  100  200  300  400  500